### PR TITLE
tests: bump pytest from 7.2.2 to 9.0.2

### PR DESCRIPTION
**Pull request by hhirtz**
pytest 7.2.2 fails on python 3.14:

```
  File "/home/hubert/dev/osrd/tests/.venv/lib/python3.14/site-packages/_pytest/assertion/rewrite.py", line 675, in run
    and isinstance(item.value, ast.Str)
                               ^^^^^^^
AttributeError: module 'ast' has no attribute 'Str'
```

### CODE REVIEW

**Comment by emersion** [comment]
Somewhat related:

- https://github.com/OpenRailAssociation/osrd/commit/102e1e3bb098f32602cb4a27c61200cc87e476a1
- https://github.com/OpenRailAssociation/osrd/commit/e148616b25a52ad45223c511dff236ce7fe42762
- https://github.com/OpenRailAssociation/osrd/commit/da06215138f2ff024ca7f5ca4e8dc3cff99ccc28

**Comment by emersion** [comment]
Any chance we could upgrade pytest instead?

**Review by shenriotpro — APPROVED** [review]

File: tests/pyproject.toml [hunk 1]
```diff
@@ -7,7 +7,7 @@ requires-python = ">=3.11"
 
 dependencies = [
   "osrd-schemas",
-  "pytest ~= 7.2.2",
+  "pytest ~= 9.0.2",
```
Comment (emersion) [inline tests/pyproject.toml:10]: Don't we need to update `tests/uv.lock` as well?

**Review by emersion — COMMENTED** [review]
`railjson_generator` is still stuck on v7:

```
python/railjson_generator/pyproject.toml:13:  "pytest ~= 7.4.3",

```

**Comment by hhirtz** [comment]
pytest 7.4.3 and 7.4.4 worked fine with python 3.14.

File: tests/pyproject.toml (hunk 1 above)
Comment (hhirtz) [reply tests/pyproject.toml:10]: updated and pushed https://github.com/OpenRailAssociation/osrd/pull/15102

**Review by emersion — APPROVED** [review]
LGTM (not tested)
